language: ruby
rvm:
  - 2.0.0
  - 2.1
  - ruby-head
bundler_args: --without development production --jobs=3 --retry=3
env:
  - GITHUB_CLIENT_ID=foo GITHUB_CLIENT_SECRET=foo SOUNDCLOUD_CLIENT_ID=foo
before_script:
  - psql -c 'create database jukebuzz_test;' -U postgres
