defaults: &defaults
  coins:
    hourly_spreaded: 6
    rewards:
      create: 20
      join: 5
      commit: 1
    balance:
      max_given: 50
    pricing_plan:
      append: 1
      prepend: 100
      move_up: 5
      move_down: 25
      delete: 50

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
